# Generated by Django 4.1.3 on 2022-11-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('detailed_description', models.TextField(max_length=500, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slamy.source')),
            ],
        ),
        migrations.CreateModel(
            name='Related_Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='slamy.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_words', to='slamy.word')),
            ],
        ),
    ]
