# Generated by Django 4.1.3 on 2022-11-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slamy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slamy.source'),
        ),
    ]
